### PR TITLE
Feature/referral

### PR DESCRIPTION
**Pull request by Deepthi-Rao**

### CODE REVIEW

**Comment by angeline-tech** [comment]
- [ ] Refer A Friend Link Copied to clipboard when button clicked
- [ ] Link takes you to the recipient to correct environment's how to play page
- [ ] How to play page displays - you were referred by ...
- [ ] Log in Form contains promocode of the referrer
- [ ] Can complete sign up of a new user using referral
- [ ] Has the referrers badge changed - If not we need to inform backend

**Comment by angeline-tech** [comment]
- [ ] Center Badge on Refer a Friend
- [ ] Before, During, After Time Test
- [ ] Log In Has got worse. Sign Up shows every time not just the first now. Needs to be fixed before merge.

**Comment by angeline-tech** [comment]
Need to fix transition state on how to play. If you are logged in and not registered and click on how to play you go straight to sign up. Questions is supposed to be like that so don't worry about that.

**Comment by angeline-tech** [comment]
Added config var REACT_APP_WEBAPP_URL to master
Did an npm run build all looks good
Login situation is fixed (i think) 
Promocode Works and is sent in the form.
Can sign up
Did a Before/During/After Test all looks good.

**Review by angeline-tech — APPROVED** [review]
Finally!

**Comment by Deepthi-Rao** [comment]
#196

**Pull request merged**
